# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Download AutoProof distribution
        run: |
          wget https://media.githubusercontent.com/media/anaumchev/autoproof/main/autoproof.tar.gz
          tar xvf autoproof.tar.gz

      #- name: Run AutoProof
      #  run: |
      #    ./ec
          
      - name: List contents
        run: |
          ls -la
      
      - name: Print WD
        run: |
          echo $PWD
          
      - name: Print home directory
        run: |
          echo $HOME
          
      - name: Print platform
        run: |
          uname -p

      - name: Run AutoProof
        run:      
          ./Eiffel_21.11/studio/spec/$ISE_PLATFORM/bin/ec_ap -verify V_ARRAY2 -config base.ecf -target base
        env:
          ISE_EIFFEL: ${{ github.workspace }}/Eiffel_21.11
          ISE_PLATFORM: linux-x86-64
          PATH: $PATH:$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin          

